version: '3.5'

services: 
    db-service:
        image: sneyd321/homeowner-service
    
        ports: 
            - 8081:8081
        
        volumes:
            - ./homeowner-service:/usr/src/app 

        restart: on-failure
   

    
        

    
